export enum MessageType {
  Audio = "audio",
  Button = "button",
  Contact = "contact",
  Empty = "empty",
  File = "file",
  Image = "image",
  List = "list",
  Location = "location",
  Media = "media",
  Poll = "poll",
  PollUpdate = "pollUpdate",
  Reaction = "reaction",
  Sticker = "sticker",
  TemplateButton = "templateButton",
  Text = "text",
  Video = "video",
}
