/// <reference types="node" />
import type { ChatStatus, IChats, IUsers, Media } from "../types";
import type { BotStatus } from "../types/Bot";
import { IMessage, IReactionMessage } from "../interfaces/IMessage";
import { IAuth } from "../interfaces/IAuth";
import { IChat } from "../interfaces/IChat";
import { IUser } from "../interfaces/IUser";
import { IBot } from "../interfaces/IBot";
import { BotEvents } from "../utils/Emmiter";
export declare class BotBase implements IBot {
    id: string;
    status: BotStatus;
    ev: BotEvents;
    connect(auth: IAuth): Promise<void>;
    reconnect(alert?: boolean): Promise<void>;
    stop(reason: any): Promise<void>;
    send(message: IMessage): Promise<IMessage>;
    editMessage(message: IMessage): Promise<void>;
    addReaction(message: IReactionMessage): Promise<void>;
    removeReaction(message: IReactionMessage): Promise<void>;
    readMessage(message: IMessage): Promise<void>;
    removeMessage(message: IMessage): Promise<void>;
    deleteMessage(message: IMessage): Promise<void>;
    downloadStreamMessage(media: Media): Promise<Buffer>;
    getBotName(): Promise<string>;
    setBotName(name: string): Promise<void>;
    getBotDescription(): Promise<string>;
    setBotDescription(description: string): Promise<void>;
    getBotProfile(): Promise<Buffer>;
    setBotProfile(image: Buffer): Promise<void>;
    getChats(): Promise<IChats>;
    setChats(chats: IChats): Promise<void>;
    getChat(chat: IChat): Promise<IChat | null>;
    setChat(chat: IChat): Promise<void>;
    addChat(chat: IChat): Promise<void>;
    removeChat(chat: IChat): Promise<void>;
    createChat(chat: IChat): Promise<void>;
    leaveChat(chat: IChat): Promise<void>;
    addUserInChat(chat: IChat, user: IUser): Promise<void>;
    removeUserInChat(chat: IChat, user: IUser): Promise<void>;
    promoteUserInChat(chat: IChat, user: IUser): Promise<void>;
    demoteUserInChat(chat: IChat, user: IUser): Promise<void>;
    changeChatStatus(chat: IChat, status: ChatStatus): Promise<void>;
    getChatUsers(chat: IChat): Promise<IUsers>;
    getChatAdmins(chat: IChat): Promise<IUsers>;
    getChatLeader(chat: IChat): Promise<IUser>;
    getChatName(chat: IChat): Promise<string>;
    setChatName(chat: IChat, name: string): Promise<void>;
    getChatDescription(chat: IChat): Promise<string>;
    setChatDescription(chat: IChat, description: string): Promise<void>;
    getChatProfile(chat: IChat): Promise<Buffer>;
    setChatProfile(chat: IChat, profile: Buffer): Promise<void>;
    getUsers(): Promise<IUsers>;
    setUsers(users: IUsers): Promise<void>;
    getUser(user: IUser): Promise<IUser | null>;
    setUser(user: IUser): Promise<void>;
    addUser(user: IUser): Promise<void>;
    removeUser(user: IUser): Promise<void>;
    unblockUser(user: IUser): Promise<void>;
    blockUser(user: IUser): Promise<void>;
    getUserName(user: IUser): Promise<string>;
    setUserName(user: IUser, name: string): Promise<void>;
    getUserDescription(user: IUser): Promise<string>;
    setUserDescription(user: IUser, description: string): Promise<void>;
    getUserProfile(user: IUser): Promise<Buffer>;
    setUserProfile(user: IUser, profile: Buffer): Promise<void>;
}
