/// <reference types="node" />
import { IMessage } from "../interfaces/Messages";
import { IUser } from "../interfaces/User";
import { IChat } from "../interfaces/Chat";
import IBot from "../interfaces/IBot";
import Auth from "../interfaces/Auth";
import { ClientType } from "./Client";
import { BotEvents } from "../utils/Emmiter";
import { IChats, ChatStatus } from "../types/Chat";
import { BotStatus } from "../types/Bot";
import { IUsers } from "../types/User";
export declare function ClientBase(): ClientType;
export declare class BotBase implements IBot {
    id: string;
    status: BotStatus;
    ev: BotEvents;
    connect(auth: Auth | string): Promise<void>;
    reconnect(alert?: boolean): Promise<void>;
    stop(reason: any): Promise<void>;
    readMessage(message: IMessage): Promise<void>;
    send(message: IMessage): Promise<IMessage>;
    removeMessage(message: IMessage): Promise<void>;
    deleteMessage(message: IMessage): Promise<void>;
    getBotName(): Promise<string>;
    setBotName(name: string): Promise<void>;
    getBotDescription(): Promise<string>;
    setBotDescription(description: string): Promise<void>;
    getBotProfile(): Promise<Buffer>;
    setBotProfile(image: Buffer): Promise<void>;
    addChat(chat: IChat): Promise<void>;
    removeChat(chat: IChat): Promise<void>;
    addUserInChat(chat: IChat, user: IUser): Promise<void>;
    removeUserInChat(chat: IChat, user: IUser): Promise<void>;
    promoteUserInChat(chat: IChat, user: IUser): Promise<void>;
    demoteUserInChat(chat: IChat, user: IUser): Promise<void>;
    changeChatStatus(chat: IChat, status: ChatStatus): Promise<void>;
    createChat(chat: IChat): Promise<void>;
    leaveChat(chat: IChat): Promise<void>;
    getChat(chat: IChat): Promise<IChat | null>;
    setChat(chat: IChat): Promise<void>;
    getChatName(chat: IChat): Promise<string>;
    setChatName(chat: IChat, name: string): Promise<void>;
    getChatDescription(chat: IChat): Promise<string>;
    setChatDescription(chat: IChat, description: string): Promise<void>;
    getChatProfile(chat: IChat): Promise<Buffer>;
    setChatProfile(chat: IChat, profile: Buffer): Promise<void>;
    getChatAdmins(chat: IChat): Promise<IUsers>;
    getChatLeader(chat: IChat): Promise<IUser>;
    getChats(): Promise<IChats>;
    setChats(chats: IChats): Promise<void>;
    addUser(user: IUser): Promise<void>;
    removeUser(user: IUser): Promise<void>;
    getUser(user: IUser): Promise<IUser | null>;
    setUser(user: IUser): Promise<void>;
    getUserName(user: IUser): Promise<string>;
    setUserName(user: IUser, name: string): Promise<void>;
    getUserDescription(user: IUser): Promise<string>;
    setUserDescription(user: IUser, description: string): Promise<void>;
    getUserProfile(user: IUser): Promise<Buffer>;
    setUserProfile(user: IUser, profile: Buffer): Promise<void>;
    unblockUser(user: IUser): Promise<void>;
    blockUser(user: IUser): Promise<void>;
    getUsers(): Promise<IUsers>;
    setUsers(users: IUsers): Promise<void>;
    addReaction(message: IMessage, reaction: string): Promise<void>;
    removeReaction(message: IMessage): Promise<void>;
}
