"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfigWAEvents = exports.WhatsAppConvertMessage = exports.WhatsAppBot = exports.MultiFileAuthState = exports.DefaultConnectionConfig = exports.DefaultCommandConfig = exports.WaitCallBack = exports.PromiseMessages = exports.BotEvents = exports.ClientEvents = exports.ClientBase = exports.User = exports.Chat = exports.Client = exports.Command = exports.BotBase = exports.EmptyMessage = exports.PollUpdateMessage = exports.PollMessage = exports.ReactionMessage = exports.FileMessage = exports.StickerMessage = exports.LocationMessage = exports.ListMessage = exports.Message = exports.AudioMessage = exports.MediaMessage = exports.VideoMessage = exports.ImageMessage = exports.ContactMessage = exports.ButtonMessage = void 0;
const ConnectionConfig_1 = require("./config/ConnectionConfig");
Object.defineProperty(exports, "DefaultConnectionConfig", { enumerable: true, get: function () { return ConnectionConfig_1.DefaultConnectionConfig; } });
const CommandConfig_1 = require("./config/CommandConfig");
Object.defineProperty(exports, "DefaultCommandConfig", { enumerable: true, get: function () { return CommandConfig_1.DefaultCommandConfig; } });
const PollUpdateMessage_1 = __importDefault(require("./messages/PollUpdateMessage"));
exports.PollUpdateMessage = PollUpdateMessage_1.default;
const ReactionMessage_1 = __importDefault(require("./messages/ReactionMessage"));
exports.ReactionMessage = ReactionMessage_1.default;
const LocationMessage_1 = __importDefault(require("./messages/LocationMessage"));
exports.LocationMessage = LocationMessage_1.default;
const ContactMessage_1 = __importDefault(require("./messages/ContactMessage"));
exports.ContactMessage = ContactMessage_1.default;
const StickerMessage_1 = __importDefault(require("./messages/StickerMessage"));
exports.StickerMessage = StickerMessage_1.default;
const ButtonMessage_1 = __importDefault(require("./messages/ButtonMessage"));
exports.ButtonMessage = ButtonMessage_1.default;
const ImageMessage_1 = __importDefault(require("./messages/ImageMessage"));
exports.ImageMessage = ImageMessage_1.default;
const VideoMessage_1 = __importDefault(require("./messages/VideoMessage"));
exports.VideoMessage = VideoMessage_1.default;
const MediaMessage_1 = __importDefault(require("./messages/MediaMessage"));
exports.MediaMessage = MediaMessage_1.default;
const AudioMessage_1 = __importDefault(require("./messages/AudioMessage"));
exports.AudioMessage = AudioMessage_1.default;
const EmptyMessage_1 = __importDefault(require("./messages/EmptyMessage"));
exports.EmptyMessage = EmptyMessage_1.default;
const ListMessage_1 = __importDefault(require("./messages/ListMessage"));
exports.ListMessage = ListMessage_1.default;
const FileMessage_1 = __importDefault(require("./messages/FileMessage"));
exports.FileMessage = FileMessage_1.default;
const PollMessage_1 = __importDefault(require("./messages/PollMessage"));
exports.PollMessage = PollMessage_1.default;
const Message_1 = __importDefault(require("./messages/Message"));
exports.Message = Message_1.default;
const Base_1 = require("./modules/Base");
Object.defineProperty(exports, "ClientBase", { enumerable: true, get: function () { return Base_1.ClientBase; } });
Object.defineProperty(exports, "BotBase", { enumerable: true, get: function () { return Base_1.BotBase; } });
const Command_1 = __importDefault(require("./modules/Command"));
exports.Command = Command_1.default;
const Client_1 = __importDefault(require("./modules/Client"));
exports.Client = Client_1.default;
const Chat_1 = __importDefault(require("./modules/Chat"));
exports.Chat = Chat_1.default;
const User_1 = __importDefault(require("./modules/User"));
exports.User = User_1.default;
const PromiseMessages_1 = __importDefault(require("./utils/PromiseMessages"));
exports.PromiseMessages = PromiseMessages_1.default;
const Emmiter_1 = require("./utils/Emmiter");
Object.defineProperty(exports, "ClientEvents", { enumerable: true, get: function () { return Emmiter_1.ClientEvents; } });
Object.defineProperty(exports, "BotEvents", { enumerable: true, get: function () { return Emmiter_1.BotEvents; } });
const WaitCallBack_1 = __importDefault(require("./utils/WaitCallBack"));
exports.WaitCallBack = WaitCallBack_1.default;
const WAConvertMessage_1 = require("./wa/WAConvertMessage");
Object.defineProperty(exports, "WhatsAppConvertMessage", { enumerable: true, get: function () { return WAConvertMessage_1.WhatsAppConvertMessage; } });
const ConfigWAEvents_1 = __importDefault(require("./wa/ConfigWAEvents"));
exports.ConfigWAEvents = ConfigWAEvents_1.default;
const Auth_1 = require("./wa/Auth");
Object.defineProperty(exports, "MultiFileAuthState", { enumerable: true, get: function () { return Auth_1.MultiFileAuthState; } });
const WhatsAppBot_1 = __importDefault(require("./wa/WhatsAppBot"));
exports.WhatsAppBot = WhatsAppBot_1.default;
__exportStar(require("./utils/Generic"), exports);
__exportStar(require("./types/Connection"), exports);
__exportStar(require("./types/Message"), exports);
__exportStar(require("./types/Client"), exports);
__exportStar(require("./types/Chat"), exports);
__exportStar(require("./types/User"), exports);
__exportStar(require("./types/Bot"), exports);
__exportStar(require("./wa/WAModules"), exports);
__exportStar(require("./wa/WAStatus"), exports);
__exportStar(require("./wa/WAModule"), exports);
__exportStar(require("./wa/WATypes"), exports);
exports.default = Client_1.default;
//# sourceMappingURL=index.js.map